eTickets/Controllers/ActorsController.cs
using eTickets.Data;
using eTickets.Data.Services;
using eTickets.Models;
using Microsoft.AspNetCore.Mvc;

namespace eTickets.Controllers {
    public class ActorsController : Controller {
        private readonly IActorsService _service;

        public ActorsController(IActorsService service) {
            _service = service;
        }

        public async Task<IActionResult> Index() {
            var allActors = await _service.GetAllAsync();
            return View(allActors);
        }

        public IActionResult Create() {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("ImageUrl, FullName, Bio")]Actor actor) {

            if (!ModelState.IsValid) {
                return View(actor);
            }

            await _service.AddAsync(actor);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Details(int id) {
            var actor = await _service.GetAsync(id);
            if (actor == null) return View("NotFound");
            return View(actor);
        }

        public async Task<IActionResult> Edit(int id) {
            var actor = await _service.GetAsync(id);
            if (actor == null) return View("NotFound");
            return View(actor);
        }

        [HttpPost]
        public async Task<IActionResult> Edit([Bind("Id, ImageUrl, FullName, Bio")] Actor actor) {

            if (!ModelState.IsValid) {
                return View(actor);
            }

            await _service.EditAsync(actor);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int id) {
            var actor = await _service.GetAsync(id);
            if (actor == null) return View("NotFound");
            return View(actor);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id) {
            var actor = await _service.GetAsync(id);
            if (actor == null) return View("NotFound");

            await _service.DeleteAsync(id);

            return RedirectToAction(nameof(Index));
        }
    }
}

eTickets/Controllers/CinemasController.cs
using eTickets.Data;
using eTickets.Data.Services;
using eTickets.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace eTickets.Controllers {
    public class CinemasController : Controller {

        private readonly ICinemasService _service;

        public CinemasController(ICinemasService service) {
            _service = service;
        }

        public async Task<IActionResult> Index() {
            var allCinemas = await _service.GetAllAsync();
            return View(allCinemas);
        }

        public async Task<IActionResult> Details(int id) {
            var cinema = await _service.GetAsync(id);
            if (cinema == null)
                return RedirectToAction(nameof(Index));
            return View(cinema);
        }

        //GET: cinemas/create
        public async Task<IActionResult> Create() {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("ImageUrl,Name,Description")] Cinema cinema) {
            if (!ModelState.IsValid) return View(cinema);
            
            await _service.AddAsync(cinema);
            return RedirectToAction(nameof(Index));
        }

        //GET: cinemas/edit/1
        public async Task<IActionResult> Edit(int id) {
            var cinema = await _service.GetAsync(id);
            if (cinema == null)
                return View("NotFound");
            return View(cinema);
        }

        [HttpPost]
        public async Task<IActionResult> Edit([Bind("Id,ImageUrl,Name,Description")] Cinema cinema) {
            if (!ModelState.IsValid) return View(cinema);

            await _service.EditAsync(cinema);
            return RedirectToAction(nameof(Index));
        }

        //GET: cinemas/delete/1
        public async Task<IActionResult> Delete(int id) {
            var cinema = await _service.GetAsync(id);
            if (cinema == null)
                return View("NotFound");
            return View(cinema);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmation(int id) {
            var cinema = await _service.GetAsync(id);
            if (cinema == null)
                return View("NotFound");
            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

eTickets/Controllers/MoviesController.cs
using eTickets.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace eTickets.Controllers {
    public class MoviesController : Controller {
        private readonly AppDbContext _context;

        public MoviesController(AppDbContext context) {
            _context = context;
        }

        public async Task<IActionResult> Index() {
            var allMovies = await _context.Movies
                .Include(n => n.Cinema)
                .OrderBy(n => n.Name)
                .ToListAsync();
            return View(allMovies);
        }
    }
}

eTickets/Controllers/ProducersController.cs
using eTickets.Data;
using eTickets.Data.Services;
using eTickets.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Net.WebSockets;

namespace eTickets.Controllers {
    public class ProducersController : Controller {

        private readonly IProducersService _service;

        public ProducersController(IProducersService service){
            _service = service;
        }

        public async Task<IActionResult> Index() {
            var allProducers = await _service.GetAllAsync();
            return View(allProducers);
        }

        //GET: producers/details/1
        public async Task<IActionResult> Details(int id) {
            var producer = await _service.GetAsync(id);
            if (producer == null)
                return View("NotFound");
            return View(producer);
        }

        //GET: producers/create
        public async Task<IActionResult> Create() {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("ImageUrl,FullName,Bio")]Producer producer) {
            if (!ModelState.IsValid) return View(producer);

            await _service.AddAsync(producer);
            return RedirectToAction(nameof(Index));
        }

        //GET: producers/edit/1
        public async Task<IActionResult> Edit(int id) {
            var producer = await _service.GetAsync(id);
            if (producer == null)
                return View("NotFound");
            return View(producer);
        }

        [HttpPost]
        public async Task<IActionResult> Edit([Bind("Id,ImageUrl,FullName,Bio")] Producer producer) {
            if (!ModelState.IsValid) return View(producer);

            await _service.EditAsync(producer);
            return RedirectToAction(nameof(Index));
        }

        //GET: producers/delete/1
        public async Task<IActionResult> Delete(int id) {
            var producer = await _service.GetAsync(id);
            if (producer == null)
                return View("NotFound");
            return View(producer);
        }

        [HttpPost, ActionName("Delete")] 
        public async Task<IActionResult> DeleteConfirmed(int id) {
            if (await _service.GetAsync(id) == null)
                return View("NotFound");
            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

eTickets/Views/Shared/NotFound.cshtml
<div class="row">
    <div class="col-6 offset-3">
        <h1>There's nothing here</h1>
        <hr />
        <a class="btn btn-success" asp-action="Index" asp-controller="Movies">Main Page</a>
        <a class="btn btn-secondary float-end" href="https://youtu.be/dQw4w9WgXcQ">Go to nothing anyway</a>
    </div>  
</div>

eTickets/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - eTickets</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/eTickets.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Movies" asp-action="Index">eTickets</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="navbar-nav">
                            <a class="nav-link text-dark" asp-controller="Movies" asp-action="Index"><i class="badge-info bi-film"></i> Movies</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" type="button"
                                id="dropdownMenuButton" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="bi bi-gear"></i> Management
                            </a>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <a class="dropdown-item" asp-controller="Cinemas" asp-action="Index"><i class="bi bi-camera-reels"></i>Cinemas</a>
                                <a class="dropdown-item" asp-controller="Producers" asp-action="Index"><i class="bi bi-headset"></i>Producers</a>
                                <a class="dropdown-item" asp-controller="Actors" asp-action="Index"><i class="bi bi-person-square"></i>Actors</a>
                            </div>
                        </li>
                    </ul>
                    <div class="row">
                        <form class="input-group my-2 my-lg-0" style="padding-right: 25px;" asp-controller="Movie" asp-action="Filter">
                            <input name="searchString" type="text" class="form-control" placeholder="Search for a movie..." />
                            <div class="input-group-append">
                                <button class="btn btn-outline-success" type="submit"><i class="bi bi-search"></i></button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - eTickets
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@@5.3.0-alpha1/dist/js/bootstrap.min.js" integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>